version: "3.8"

services:
  server:
    image: judge0/judge0:1.13.1
    ports:
      - "2358:2358"
    environment:
      PORT: 2358
      POSTGRES_HOST: db
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ENABLE_NETWORK: "false"
      ENABLE_ADDITIONAL_FILES: "false"
      MAX_CPU_TIME_LIMIT: "2"
      MAX_MEMORY_LIMIT: "262144"

  worker:
    image: judge0/judge0:1.13.1
    command: ["bundle", "exec", "rake", "resque:work"]
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  data:
